NEW = 'NEW'
PENDING = 'PENDING'
WAITLISTED = 'WAITLISTED'
ACCEPTED = 'ACCEPTED'
REJECTED = 'REJECTED'
DECLINED = 'DECLINED'
SIGNING = 'SIGNING'
CONFIRMED = 'CONFIRMED'
ADMIN = 'ADMIN'

STATUS_LEVEL = {
    NEW: 0,
    PENDING: 1,
    WAITLISTED: 2,
    ACCEPTED: 3,
    REJECTED: 4,
    DECLINED: 5,
    SIGNING: 6,
    CONFIRMED: 7,
    ADMIN: 999,
}
