"""empty message

Revision ID: 013b5c571b68
Revises: 2db13dc62333
Create Date: 2016-09-10 02:26:04.344347

"""

# revision identifiers, used by Alembic.
revision = '013b5c571b68'
down_revision = '2db13dc62333'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('med_auth_signature_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('waiver_signature_id', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'waiver_signature_id')
    op.drop_column('users', 'med_auth_signature_id')
    ### end Alembic commands ###
