"""empty message

Revision ID: 02e904b1b042
Revises: 5fe2987ca442
Create Date: 2016-07-18 23:54:32.068716

"""

# revision identifiers, used by Alembic.
revision = '02e904b1b042'
down_revision = '5fe2987ca442'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_roles', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_column('user_roles', 'role_id')
    ### end Alembic commands ###
