"""empty message

Revision ID: 0ed2f485a3fe
Revises: 72eda896c4c2
Create Date: 2016-08-18 13:11:33.425941

"""

# revision identifiers, used by Alembic.
revision = '0ed2f485a3fe'
down_revision = '72eda896c4c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role')
    op.add_column('user_roles', sa.Column('role_id', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_roles', 'role_id')
    op.create_table('role',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'role_pkey')
    )
    ### end Alembic commands ###
