"""empty message

Revision ID: 1739031ab894
Revises: a6ce8568edc3
Create Date: 2016-08-14 15:31:18.250914

"""

# revision identifiers, used by Alembic.
revision = '1739031ab894'
down_revision = 'a6ce8568edc3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('name', sa.String(length=64), nullable=True))
    op.drop_column('user_roles', 'role_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('role_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('user_roles', 'name')
    ### end Alembic commands ###
