"""empty message

Revision ID: 230933cec844
Revises: c2a7e6589552
Create Date: 2017-10-01 20:07:24.155770

"""

# revision identifiers, used by Alembic.
revision = '230933cec844'
down_revision = 'c2a7e6589552'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('time_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'time_created')
    # ### end Alembic commands ###
