"""empty message

Revision ID: 2ae4701a60b4
Revises: 013b5c571b68
Create Date: 2016-09-11 15:43:53.495932

"""

# revision identifiers, used by Alembic.
revision = '2ae4701a60b4'
down_revision = '013b5c571b68'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('school_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('school_name', sa.String(length=255), nullable=True))
    op.drop_column('users', 'school')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('school', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'school_name')
    op.drop_column('users', 'school_id')
    ### end Alembic commands ###
