"""empty message

Revision ID: 2db13dc62333
Revises: e17cc549fd65
Create Date: 2016-09-09 22:51:23.996959

"""

# revision identifiers, used by Alembic.
revision = '2db13dc62333'
down_revision = 'e17cc549fd65'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'resume_uploaded')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('resume_uploaded', sa.BOOLEAN(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
