"""empty message

Revision ID: 2e739de9f292
Revises: 4a9fbca0f174
Create Date: 2017-09-21 17:01:46.092314

"""

# revision identifiers, used by Alembic.
revision = '2e739de9f292'
down_revision = '4a9fbca0f174'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'team_id')
    # ### end Alembic commands ###
