"""empty message

Revision ID: 337ae4592f05
Revises: 02e904b1b042
Create Date: 2016-07-30 15:17:08.221663

"""

# revision identifiers, used by Alembic.
revision = '337ae4592f05'
down_revision = '02e904b1b042'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('race', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('resume_uploaded', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'resume_uploaded')
    op.drop_column('users', 'race')
    ### end Alembic commands ###
