"""empty message

Revision ID: 43d9a0ac54ec
Revises: c5ef5707e2e5
Create Date: 2016-10-08 20:02:46.121467

"""

# revision identifiers, used by Alembic.
revision = '43d9a0ac54ec'
down_revision = 'c5ef5707e2e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volunteers')
    ### end Alembic commands ###
