"""empty message

Revision ID: 4a9fbca0f174
Revises: abe09b6193c4
Create Date: 2017-09-21 16:53:32.507961

"""

# revision identifiers, used by Alembic.
revision = '4a9fbca0f174'
down_revision = 'abe09b6193c4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'users_team_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'team_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'users_team_id_fkey', 'users', 'teams', ['team_id'], ['id'], ondelete=u'CASCADE')
    # ### end Alembic commands ###
