"""empty message

Revision ID: 5ab8dba1ec59
Revises: 938a29632f3d
Create Date: 2017-10-02 13:45:40.220872

"""

# revision identifiers, used by Alembic.
revision = '5ab8dba1ec59'
down_revision = '938a29632f3d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('why_travel_reimbursement', sa.Text(), nullable=True))
    op.drop_column('users', 'most_nervous')
    op.drop_column('users', 'expectations')
    op.drop_column('users', 'most_excited')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('most_excited', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('expectations', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('most_nervous', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('users', 'why_travel_reimbursement')
    # ### end Alembic commands ###
