"""empty message

Revision ID: 5cd6fe66e980
Revises: 7bca00e90515
Create Date: 2017-10-11 22:30:55.742283

"""

# revision identifiers, used by Alembic.
revision = '5cd6fe66e980'
down_revision = '7bca00e90515'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('accepted_travel_reimbursement', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'accepted_travel_reimbursement')
    # ### end Alembic commands ###
