"""empty message

Revision ID: 5f3e11f09e83
Revises: 946c6ea709d6
Create Date: 2016-09-30 11:19:59.902435

"""

# revision identifiers, used by Alembic.
revision = '5f3e11f09e83'
down_revision = '946c6ea709d6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('relative_name', sa.String(length=128), nullable=True),
    sa.Column('relative_email', sa.String(length=128), nullable=True),
    sa.Column('relative_num', sa.String(length=32), nullable=True),
    sa.Column('allergies', sa.String(length=128), nullable=True),
    sa.Column('medications', sa.String(length=128), nullable=True),
    sa.Column('special_health_needs', sa.String(length=128), nullable=True),
    sa.Column('medical_signature', sa.String(length=64), nullable=True),
    sa.Column('medical_date', sa.Date(), nullable=True),
    sa.Column('indemnification_signature', sa.String(length=64), nullable=True),
    sa.Column('indemnification_date', sa.Date(), nullable=True),
    sa.Column('photo_signature', sa.String(length=64), nullable=True),
    sa.Column('photo_date', sa.Date(), nullable=True),
    sa.Column('time_signed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waivers')
    ### end Alembic commands ###
