"""empty message

Revision ID: 683ada20cd0d
Revises: 07fe229dd548
Create Date: 2017-10-01 15:51:53.016332

"""

# revision identifiers, used by Alembic.
revision = '683ada20cd0d'
down_revision = '07fe229dd548'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'team_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('team_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
