"""empty message

Revision ID: 6ee2237532bf
Revises: 5f3e11f09e83
Create Date: 2016-10-01 12:06:50.733367

"""

# revision identifiers, used by Alembic.
revision = '6ee2237532bf'
down_revision = '5f3e11f09e83'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waivers', sa.Column('ut_eid', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waivers', 'ut_eid')
    ### end Alembic commands ###
