"""empty message

Revision ID: 72eda896c4c2
Revises: e1414a1ae95e
Create Date: 2016-08-18 13:10:54.528806

"""

# revision identifiers, used by Alembic.
revision = '72eda896c4c2'
down_revision = 'e1414a1ae95e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'role_name_key', 'role', type_='unique')
    op.drop_constraint(u'user_roles_role_id_fkey', 'user_roles', type_='foreignkey')
    op.drop_column('user_roles', 'role_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'user_roles_role_id_fkey', 'user_roles', 'role', ['role_id'], ['id'], ondelete=u'CASCADE')
    op.create_unique_constraint(u'role_name_key', 'role', ['name'])
    ### end Alembic commands ###
