"""empty message

Revision ID: 74de4523df7a
Revises: c322c83ead7d
Create Date: 2017-10-02 01:16:32.801380

"""

# revision identifiers, used by Alembic.
revision = '74de4523df7a'
down_revision = 'c322c83ead7d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_leader', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('time_team_join', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'time_team_join')
    op.drop_column('users', 'is_leader')
    # ### end Alembic commands ###
