"""empty message

Revision ID: 7bca00e90515
Revises: 5ab8dba1ec59
Create Date: 2017-10-10 04:13:13.598430

"""

# revision identifiers, used by Alembic.
revision = '7bca00e90515'
down_revision = '5ab8dba1ec59'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_travel_reimbursement', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_campus_ambassador', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_campus_ambassador')
    op.drop_column('users', 'has_travel_reimbursement')
    # ### end Alembic commands ###
