"""empty message

Revision ID: 826d878bb2d0
Revises: 2e739de9f292
Create Date: 2017-10-01 23:30:32.372366

"""

# revision identifiers, used by Alembic.
revision = '826d878bb2d0'
down_revision = '2e739de9f292'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_leader', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('time_team_join', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'time_team_join')
    op.drop_column('users', 'is_leader')
    # ### end Alembic commands ###
