"""empty message

Revision ID: 87a51f844ed4
Revises: f70ba6178b11
Create Date: 2016-07-18 22:59:08.874022

"""

# revision identifiers, used by Alembic.
revision = '87a51f844ed4'
down_revision = 'f70ba6178b11'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('type', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'type')
    ### end Alembic commands ###
