"""empty message

Revision ID: 938a29632f3d
Revises: 74de4523df7a
Create Date: 2017-10-02 04:00:50.992241

"""

# revision identifiers, used by Alembic.
revision = '938a29632f3d'
down_revision = '74de4523df7a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_leader')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_leader', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
