"""empty message

Revision ID: 946c6ea709d6
Revises: 7575d7663b8b
Create Date: 2016-09-18 02:14:07.113140

"""

# revision identifiers, used by Alembic.
revision = '946c6ea709d6'
down_revision = '7575d7663b8b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
