"""empty message

Revision ID: abe09b6193c4
Revises: af836bb0d2ac
Create Date: 2017-09-21 16:04:46.836192

"""

# revision identifiers, used by Alembic.
revision = 'abe09b6193c4'
down_revision = 'af836bb0d2ac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tname', sa.String(length=255), nullable=True),
    sa.Column('team_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'users', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column(u'users', 'team_id')
    op.drop_table('teams')
    # ### end Alembic commands ###
