"""empty message

Revision ID: c2a7e6589552
Revises: 683ada20cd0d
Create Date: 2017-10-01 16:34:11.066121

"""

# revision identifiers, used by Alembic.
revision = 'c2a7e6589552'
down_revision = '683ada20cd0d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'teams', ['tname'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'teams', type_='unique')
    # ### end Alembic commands ###
