"""empty message

Revision ID: c3cb8f4b7634
Revises: af836bb0d2ac
Create Date: 2017-09-24 00:41:50.260666

"""

# revision identifiers, used by Alembic.
revision = 'c3cb8f4b7634'
down_revision = 'af836bb0d2ac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('campus_ambassador', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('expectations', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('most_excited', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('most_nervous', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('needs_travel_reimbursement', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('workshops', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'workshops')
    op.drop_column('users', 'needs_travel_reimbursement')
    op.drop_column('users', 'most_nervous')
    op.drop_column('users', 'most_excited')
    op.drop_column('users', 'expectations')
    op.drop_column('users', 'campus_ambassador')
    # ### end Alembic commands ###
