"""empty message

Revision ID: c97aa9ccd33b
Revises: c3cb8f4b7634
Create Date: 2017-09-30 03:25:55.824550

"""

# revision identifiers, used by Alembic.
revision = 'c97aa9ccd33b'
down_revision = 'c3cb8f4b7634'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('campus_ambassadors_application', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('facebook_account', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'facebook_account')
    op.drop_column('users', 'campus_ambassadors_application')
    # ### end Alembic commands ###
