"""empty message

Revision ID: e1414a1ae95e
Revises: 337ae4592f05
Create Date: 2016-07-30 17:49:18.786874

"""

# revision identifiers, used by Alembic.
revision = 'e1414a1ae95e'
down_revision = '337ae4592f05'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_hackathon', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'first_hackathon')
    ### end Alembic commands ###
